workers:

    # compiled CSS automatically
    tailwind:
        cmd: ['symfony', 'console', 'tailwind:build', '--watch']

    # auto start Docker compose when starting server (available since Symfony CLI 5.7.0)
    docker_compose: ~
